{
    'name': "Intervlag Email Templates",
    'version': '16.0.1.0.0',
    'summary': """Intervlag email template""",
    'description': """T""",
    'category': 'Extra tools',
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ["mail", "sale", "portal"],
    'data': [
        "data/intervlag_rest_password.xml",
        "data/delivery_send_by_email1.xml",
        "data/invoicing_Invoice_email1.xml",
        "data/late_order_mo.xml",
        "data/late_shipment.xml",
        "data/gift_not_selected.xml",
        "data/gift_selected.xml",
        "data/sale_order_send_by_email.xml",
        "data/online_order_confirmation.xml",
        "data/sale_of_the_day.xml",
        "data/send_quotation_email.xml",
        "data/send_quotation_with_proof.xml",
        "data/vlaggenmasten_sale_order.xml",
        "data/user_portal_access.xml",
        "data/intervalg_new_user_registration_email.xml",
    ],
    'license': "AGPL-3",
    'images': [],
    'installable': True,
    'application': False,
    # 'pre_init_hook':"_intervlag_email_templates",
}
